name: Perseus Build

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'Select Region'
        required: true
        type: choice
        options:
          - 'EN'
          - 'JP'
          - 'KR'
          - 'TW'
          - 'CN'


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install build-tools
        run: |
          yes | sdkmanager --install "build-tools;32.0.0"

      # APK build process
      - name: Determine Bundle ID
        id: bundle_id
        run: |
          case "${{ github.event.inputs.region }}" in
          "EN")
            echo "BUNDLE_ID=com.YoStarEN.AzurLane" >> $GITHUB_ENV
            ;;
          "JP")
            echo "BUNDLE_ID=com.YoStarJP.AzurLane" >> $GITHUB_ENV
            ;;
          "KR")
            echo "BUNDLE_ID=kr.txwy.and.blhx" >> $GITHUB_ENV
            ;;
          "TW")
            echo "BUNDLE_ID=com.hkmanjuu.azurlane.gp" >> $GITHUB_ENV
            ;;
          "CN")
            echo "BUNDLE_ID=com.bilibili.azurlane" >> $GITHUB_ENV
            ;;
          esac
        shell: bash

      - name: Build Perseus APK
        run: ./patch_perseus.sh ${{ env.BUNDLE_ID }}

      - name: Zipalign and Sign Android release
        run: ./zipalign_sign.sh

      # 创建分卷压缩包
      - name: Create split archives
        run: |
          # 设置分卷大小（这里设置为50MB，可根据需要调整）
          SPLIT_SIZE=800M
          
          # 查找生成的APK文件
          APK_FILE=$(find build -name "*.apk" | head -n 1)
          
          if [ -z "$APK_FILE" ]; then
            echo "Error: No APK file found in build directory!"
            exit 1
          fi
          
          # 创建分卷压缩包（仅存储，不压缩）
          echo "Creating split archives for: $APK_FILE"
          zip -0 -r -s $SPLIT_SIZE "perseus_split.zip" "$APK_FILE"
          
          # 重命名分卷文件
          for file in perseus_split.z*; do
            if [[ $file == perseus_split.zip ]]; then
              mv "$file" "perseus_split.zip.00"
            else
              # 确保分卷编号是两位数
              part_num=${file##perseus_split.z}
              if [ ${#part_num} -eq 1 ]; then
                mv "$file" "perseus_split.zip.0$part_num"
              fi
            fi
          done
          
          # 列出生成的分卷文件
          echo "Generated split files:"
          ls -la perseus_split.zip.*

      # 发布APK和分卷压缩包
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ github.event.inputs.region }}-v${{ env.PERSEUS_VERSION }}"
          name: "Azurlane Perseus ${{ github.event.inputs.region }} Release v${{ env.PERSEUS_VERSION }}"
          artifacts: "build/*.apk,perseus_split.zip.*"
          allowUpdates: true
