name: Perseus Build

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'Select Region'
        required: true
        type: choice
        options:
          - 'EN'
          - 'JP'
          - 'KR'
          - 'TW'
          - 'CN'


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install build-tools
        run: |
          yes | sdkmanager --install "build-tools;32.0.0"

      # APK build process
      - name: Determine Bundle ID
        id: bundle_id
        run: |
          case "${{ github.event.inputs.region }}" in
          "EN")
            echo "BUNDLE_ID=com.YoStarEN.AzurLane" >> $GITHUB_ENV
            ;;
          "JP")
            echo "BUNDLE_ID=com.YoStarJP.AzurLane" >> $GITHUB_ENV
            ;;
          "KR")
            echo "BUNDLE_ID=kr.txwy.and.blhx" >> $GITHUB_ENV
            ;;
          "TW")
            echo "BUNDLE_ID=com.hkmanjuu.azurlane.gp" >> $GITHUB_ENV
            ;;
          "CN")
            echo "BUNDLE_ID=com.bilibili.azurlane" >> $GITHUB_ENV
            ;;
          esac
        shell: bash

      - name: Build Perseus APK
        run: ./patch_perseus.sh ${{ env.BUNDLE_ID }}

      - name: Zipalign and Sign Android release
        run: ./zipalign_sign.sh
                    
      # Publish APK
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ github.event.inputs.region }}-v${{ env.PERSEUS_VERSION }}"
          name: "Perseus Release ${{ github.event.inputs.region }} v${{ env.PERSEUS_VERSION }}"
          artifacts: "build/*.apk"
          allowUpdates: true
